keys:
  users:
    # age-keygen -o ~/.config/sops/age/keys.txt
    # age-keygen -y ~/.config/sops/age/keys.txt
    - &vivian age1q5ap3h80unrf7uz0d5nwm3atp3f5kry0f3ucj44r3xe5ckwtg5fs0khp4v
  hosts:
    # nix-shell -p ssh-to-age --run 'cat /etc/ssh/ssh_host_ed25519_key.pub | ssh-to-age'
    - &test-node age1hpptsyvz8n924hkpcunmkwyfd9xdecaj5y0whk3cs0t45u983qestfwjtc
    - &n1 age1xm0c2t2az2tucxmaaa7lw3vmsxg6ntrcvy472h98y0egkee85pcsgx72x3
    - &n2 age1n5dzvy69rk0gmulndczfwjhjkaq329j3fd9fme3ehgwtvhc7zfnsmgqc48
    - &n3 age1xk0y5pk2yerlecgldv22sdv6ty98jgjcz20mzfyxsv940yq37sesautru6
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    # mit keygroups wird definiert, welche keys zugang zu den secrets haben
    # neue keys updaten: sops updatekeys secrets/secrets.yaml
    key_groups:
      - age:
        - *vivian
        - *test-node
        - *n1
        - *n2
        - *n3
