require "json"

VAGRANT_SSH_PRIVATE_KEY = File.expand_path(
  ".bootstrap/bootstrap-key",
  __dir__
)

TARGETS_FILE = File.join(
  __dir__,
  ".deploy-targets.json"
)

BRIDGE_INTERFACE = File.expand_path(
  "bridge-interface.sh",
  __dir__
)

bridge_interface = `#{BRIDGE_INTERFACE}`.strip

abort "Could not determine host bridge interface" if bridge_interface.empty?

unless File.exist?(TARGETS_FILE)
  abort <<~MSG
    Missing #{TARGETS_FILE}

    Run:
      ./deploy.sh targets
  MSG
end

targets = JSON.parse(File.read(TARGETS_FILE))

nodes = targets.select do |_name, target|
  target["isVirtualMachine"] == true
end

Vagrant.configure("2") do |config|
  config.vm.box = "nixos-vbox"

  config.ssh.username = "root"
  config.ssh.insert_key = false
  config.ssh.private_key_path = VAGRANT_SSH_PRIVATE_KEY
  config.ssh.connect_timeout = 300
  config.ssh.connect_retries = 50

  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.allow_fstab_modification = false

  nodes.each do |name, target|
    ip = target["ipv4Address"]
    interface = target["interface"]

    config.vm.define name do |node|
      node.vm.network "public_network",
        bridge: bridge_interface,
        auto_config: false
      node.vm.network "private_network",
        ip: ip,
        auto_config: false

      node.vm.provision "shell",
        privileged: true,
        inline: <<-SHELL
          ip link set #{interface} up
          ip addr flush dev #{interface}
          ip addr add #{ip}/24 dev #{interface}
        SHELL

      node.vm.provider "virtualbox" do |vb|
        vb.memory = 6144
        vb.cpus = 4
        vb.name = name
        vb.check_guest_additions = false
      end
    end
  end
end